In [45]:
a=np.arange(4)

In [46]:
a

array([0, 1, 2, 3])

In [47]:
a[[0,-1]]

array([0, 3])

In [48]:
a[[True, True,False, False]]

array([0, 1])

In [50]:
a[a>=2]

array([2, 3])

In [51]:
a>=2

array([False, False,  True,  True])

In [52]:
a[~(a>a.mean())]

array([0, 1])

In [53]:
a.mean()

1.5

In [55]:
A=np.array([
    [1,5,8,6],
    [75,5,987,6]   
    
])

In [56]:
A>30

array([[False, False, False, False],
       [ True, False,  True, False]])

In [59]:
import sys

In [60]:
sys.getsizeof(1)

28

In [62]:
np.random.random(size=2)

array([0.55969173, 0.18578212])

In [63]:
np.random.normal(size=2)

array([-0.53672723, -0.59950806])

In [64]:
np.random.rand(2,4)

array([[0.04891878, 0.76053525, 0.20400648, 0.8876279 ],
       [0.73832676, 0.52882339, 0.36987374, 0.20303904]])

In [65]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
np.arange(2,5)

array([2, 3, 4])

In [67]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])